@startuml
class ApiEndpointTests {
    + <<async>> TestAPIUp() : Task
    - <<async>> TestSessionCreation() : Task
    - <<async>> TestSessionList() : Task<string>
    - <<async>> TestSessionDelete(sID:string) : Task
    - <<async>> TestCreateArticle(sID:string) : Task
    - <<async>> TestRetriveSession(sID:string) : Task
    + <<async>> Test() : Task
}
@enduml
